### ISSUE TITLE
failed with ./ws build release

### ISSUE THREAD

**Issue by dreamqin68** [por-se/workspace#1]
Hi,

When I followed the `QuickStart` instructions to build, there is an error.
```
[z3 (release)] CMake Error: The source directory "/home/workspace/.build/z3-release-Bjprr7kZFTgJCsZJ" does not exist.
[z3 (release)] Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "/home/workspace/.venv/bin/build", line 33, in <module>
    sys.exit(load_entry_point('workspace', 'console_scripts', 'build')())
  File "/home/workspace/ws-src/workspace/bin/build.py", line 34, in main
    workspace.build()
  File "/home/workspace/ws-src/workspace/workspace.py", line 98, in build
    build.build(self)
  File "/home/workspace/ws-src/workspace/recipes/z3.py", line 110, in build
    CMakeRecipeMixin.build(self, workspace)
  File "/home/workspace/ws-src/workspace/build_systems/cmake_recipe_mixin.py", line 112, in build
    self.cmake.configure(workspace,
  File "/home/workspace/ws-src/workspace/build_systems/__init__.py", line 140, in configure
    run_with_prefix(config_call, self.output_prefix, env=env, check=True)
  File "/home/workspace/ws-src/workspace/util.py", line 163, in run_with_prefix
    raise Exception(f'Command {command[0]} failed with non-zero exit status {status}')
Exception: Command cmake failed with non-zero exit status 256
```
How to solve this problem? Thanks.

**Comment by jbuening** [comment]
Hi @dreamqin68,

thanks for wanting to try por-se! I just checked `./ws build` with a fresh clone of this repo and it still starts building z3 as expected. Is this what you executed or did you perfom any steps in between? Your paths look a bit weird, but I assume that you just removed your user directory following `/home/`. Did any warnings or non-fatal errors occur prior to the above message?

With only the information provided above, let me suggest the following:
1. Could you please check if there is any directory in `/home/workspace/.build/`, possibly with `z3-release` prefix?
2. Maybe you can see what happens if you execute `./ws clean` or `./ws dist-clean` (assuming you did not make any changes to any of our source code that you would like to keep; the latter command removes all source directories) before trying `./ws build` again.

Please let me know if that helps somehow. Otherwise, I'm happy to assist you further if you can provide me with some more information about your enviroment (like OS, shell) and preferably a complete log.

**Comment by dreamqin68** [comment]
Hi @jbuening,

I just use one command `./ws build`. I currently only hope to be able to successfully build. There are no warnings or non-fatal errors that occur prior to the above message.

1. in  `/home/workspace/.build/`, there is the only `uclibc-locale/` folder.
2. I have tried using `./ws dist-clean`, and building again, but the same error still existed. 
3. OS: Ubuntu 18.04.6 LTS

I found that there are `./workspace/y/v1/github.com/Z3Prover` folder and `./workspace/z3/` folder.

Thanks for your help.

**Comment by jbuening** [comment]
Thanks for your OS information, that helped to quickly reproduce and understand the issue.

The CMake version provided with Ubuntu 18.04.6 LTS is 3.10, however, our scripts rely on the `-B` option of CMake which was introduced in 3.13 (released in Nov 2018), as it seems. While it is possible that this is the only issue with running our software on your system, it is quite unlikely, given that we never tested our scripts or our KLEE fork with similarly dated software versions and we are not able to provide support for a wide range of software versions. I am sorry that I am not able to offer any further help with this.

However, you might want to try our [artifact](https://zenodo.org/record/5771252), where we provide VM images that already contain built versions of POR-SE, as well as these workspace scripts.

Alternatively, you could try running our scripts on Ubuntu 20.04.3 LTS or any more current distribution (possibly in a docker container). If you run into issues with these, I am more confident we are able to resolve them and provide you with a patch if necessary.

Given that this is actually an issue with a particular version of Ubuntu LTS, I will close this for now. If you give our artifact or a more recent OS a try and run into further issues, please feel free to open another issue or contact me via email.
